version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  wallet-db:
    image: postgres:15.1-alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=super_secret
    ports:
      - '5432:5432'
    volumes:
      - wallet-db:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  wallet-service:
    build: ./wallet-service
    ports:
      - '8080:8080'
    depends_on:
      - wallet-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wallet-db:5432/wallet
      - SPRING_DATASOURCE_USERNAME=wallet
      - SPRING_DATASOURCE_PASSWORD=super_secret

volumes:
  wallet-db:
    driver: local