version: '3.8'
services:
  wallet-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - wallet-cache:/data

  wallet-db:
    image: postgres:15.1-alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=super_secret
    ports:
      - '5432:5432'
    volumes:
      - wallet-db:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  wallet-service:
    build: ./wallet-service
    ports:
      - '8080:8080'
    depends_on:
      - wallet-cache
      - wallet-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wallet-db:5432/wallet
      - SPRING_DATASOURCE_USERNAME=wallet
      - SPRING_DATASOURCE_PASSWORD=super_secret
      - SPRING_CACHE_TYPE=redis
      - SPRING_REDIS_HOST=wallet-cache
      - SPRING_REDIS_PORT=6379

volumes:
  wallet-cache:
    driver: local
  wallet-db:
    driver: local