version: '3.8'
services:
  wallet-db:
    image: postgres:15.1-alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=super_secret
    ports:
      - '5432:5432'
    volumes:
      - wallet-db:/var/lib/postgresql/data
      - ./wallet_db_initial_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  wallet-service:
    build: ./wallet-service
    ports:
      - '8080:8080'
    depends_on:
      - wallet-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wallet-db:5432/wallet
      - SPRING_DATASOURCE_USERNAME=wallet
      - SPRING_DATASOURCE_PASSWORD=super_secret

volumes:
  wallet-db:
    driver: local